viplanner:
  model_path: "/scratch/minh/school/282_project/PlanningInterpretability/models"
  data_path: "/scratch/minh/school/282_project/carla"
  camera_cfg_path: "/scratch/minh/school/282_project/carla/camera_extrinsic.txt"
  point_cloud_path: "/scratch/minh/school/282_project/carla/cloud.ply"
  device: "cuda:6"

hydra:
  run:
    dir: .
