viplanner:
  model_path: "/Users/phoebe.wang/Desktop/CS182_Final_Project/PlanningInterpretability/models"
  data_path: "/Users/phoebe.wang/Desktop/CS182_Final_Project/carla"
  camera_cfg_path: "/Users/phoebe.wang/Desktop/CS182_Final_Project/carla/camera_extrinsic.txt"
  device: "cpu"

hydra:
  run:
    dir: .
