viplanner:
  model_path: "/Users/ryan/Desktop/python/182/PlanningInterpretability/models"
  data_path: "/Users/ryan/Desktop/python/182/carla"
  camera_cfg_path: "/Users/ryan/Desktop/python/182/carla/camera_extrinsic.txt"
  device: "cpu"

hydra:
  run:
    dir: .